[package]
name = "aoc-01"
version = "0.1.0"
authors = ["alyssa"]
edition = "2018"

[dependencies]

[[bin]]
name = "aoc-01"
path = "01/main.rs"

[[bin]]
name = "aoc-02"
path = "02/main.rs"

[[bin]]
name = "aoc-03"
path = "03/main.rs"

[[bin]]
name = "aoc-04"
path = "04/main.rs"